/* Sourced leads live in IndexedDB, not in the app state row.
 *
 * The whole app state is one JSON row in mc_state, mirrored into localStorage and a backup key.
 * Measured with leads in it: one market 2.0 MB, two markets 4.0 MB, and the third import does not
 * survive a reload. The engine has 8 783 leads with an angle across six cities and twelve more
 * cities to run, so the blob was never going to hold them.
 *
 * What stays in the synced state is everything he creates: the stage he dragged a card to, a note,
 * a logged call, the reason something was lost. Those live on real Contact rows and keep syncing
 * to Supabase exactly as before. What moves here is only what the engine measured, which is
 * regenerable by re-running the export, so holding it per-device costs nothing if a device is
 * wiped. That split is the point: nothing precious is device-local, and nothing regenerable is
 * taking space in a 5 MB quota.
 */
import type { LeadInfo, LeadOffers } from './types'

const DB = 'mc-leads'
const VERSION = 1
const LEADS = 'leads'
const META = 'meta'

export interface LeadRow {
  placeKey: string
  name: string
  phone?: string
  email?: string
  lead: LeadInfo
}

let dbp: Promise<IDBDatabase> | null = null

function open(): Promise<IDBDatabase> {
  if (dbp) return dbp
  dbp = new Promise((resolve, reject) => {
    if (typeof indexedDB === 'undefined') { reject(new Error('no indexedDB')); return }
    const req = indexedDB.open(DB, VERSION)
    req.onupgradeneeded = () => {
      const db = req.result
      if (!db.objectStoreNames.contains(LEADS)) db.createObjectStore(LEADS, { keyPath: 'placeKey' })
      if (!db.objectStoreNames.contains(META)) db.createObjectStore(META)
    }
    req.onsuccess = () => resolve(req.result)
    req.onerror = () => reject(req.error)
  })
  return dbp
}

function tx<T>(store: string, mode: IDBTransactionMode, run: (s: IDBObjectStore) => IDBRequest<T>): Promise<T> {
  return open().then((db) => new Promise<T>((resolve, reject) => {
    const t = db.transaction(store, mode)
    const r = run(t.objectStore(store))
    r.onsuccess = () => resolve(r.result)
    r.onerror = () => reject(r.error)
  }))
}

export async function putLeads(rows: LeadRow[]): Promise<{ added: number; updated: number }> {
  const db = await open()
  const existing = new Set(await allKeys())
  let added = 0, updated = 0
  /* One transaction for the whole batch. Eight thousand separate ones is a visibly frozen tab. */
  await new Promise<void>((resolve, reject) => {
    const t = db.transaction(LEADS, 'readwrite')
    const s = t.objectStore(LEADS)
    for (const r of rows) {
      if (!r.placeKey || !r.name) continue
      if (existing.has(r.placeKey)) updated++; else added++
      s.put(r)
    }
    t.oncomplete = () => resolve()
    t.onerror = () => reject(t.error)
    t.onabort = () => reject(t.error)
  })
  return { added, updated }
}

export function allLeads(): Promise<LeadRow[]> {
  return tx<LeadRow[]>(LEADS, 'readonly', (s) => s.getAll())
}
export function allKeys(): Promise<string[]> {
  return tx<IDBValidKey[]>(LEADS, 'readonly', (s) => s.getAllKeys()).then((k) => k.map(String))
}
export function countLeads(): Promise<number> {
  return tx<number>(LEADS, 'readonly', (s) => s.count())
}
export function deleteLead(placeKey: string): Promise<void> {
  return tx<undefined>(LEADS, 'readwrite', (s) => s.delete(placeKey)).then(() => undefined)
}
export function clearLeads(): Promise<void> {
  return tx<undefined>(LEADS, 'readwrite', (s) => s.clear()).then(() => undefined)
}

/* The offer catalogue is tiny (a dozen entries for two markets) but it belongs with the leads it
   describes, not in the synced state, for the same reason: it is regenerated by the exporter. */
export function putOffers(offers: LeadOffers): Promise<void> {
  return tx<IDBValidKey>(META, 'readwrite', (s) => s.put(offers, 'offers')).then(() => undefined)
}
export function getOffers(): Promise<LeadOffers> {
  return tx<LeadOffers | undefined>(META, 'readonly', (s) => s.get('offers')).then((o) => o ?? {})
}
